### ISSUE TITLE
Activities should be an icon or a label "Overview"

### ISSUE THREAD

**Issue by me4oslav** [ozonos/atom-panel#9]
If possible instead of label activities, we should display label "Overview" or symbolic icon (view-more-symbolic) from our icon theme.
Check the attached screenshot.
![screenshot from 2015-02-23 13 56 12](https://cloud.githubusercontent.com/assets/1658870/6327465/fa7d6882-bb64-11e4-8a32-62b971ab2a99.png)

This is achievable with the "Activities Configurator" gnome-shell extension (https://extensions.gnome.org/extension/358/activities-configurator/), however:
A) We need it to just set the label to "overview" or use the "view-more-symbolic" icon
B) It doesn't respect symbol icons recolouring, it hardcodes the icon to whatever .svg file one has picked
C) We don't needs its additional option

If we're to use it in our panel, we must fix these three things.

**Comment by me4oslav** [comment]
Screenshots with icon and with label, btw.
![screenshot from 2015-02-25 11 52 48](https://cloud.githubusercontent.com/assets/1658870/6368405/08a41f88-bce5-11e4-8436-061b76e98bdb.png)
![screenshot from 2015-02-25 11 53 46](https://cloud.githubusercontent.com/assets/1658870/6368406/08a89130-bce5-11e4-8b56-5f08b6e091b6.png)

**Comment by cldx** [comment]
Okay here we go. So how do we get the Icon into the Panel in the most simple way. I put this here so @smartfuse can implement it, cause well, he's assigned and this way he can implement it AND understand what's going on.

Disclaimer: This is raw code, it's not meant to be ultima ratio and there are most likely ways to write it nicer or simpler. The things is though: It works yo! And i added a lot of comments for everybody to understand what's going on.

First off lets define some vars in the head part of the file to store our stuff into, right below all the constants put:
```
    let activitiesButtonActor;
    let labelActor;
    let iconActor;
```

Now on to the nitt-gritty, lets write a function that will get us the ActivitiesButton, this goes into the 'Extension' class :
```
	getActivitiesButton: function(){
		/* Lets find the Activities Button */
		/* we need to iterate over the children in _leftBox cause we can't tell for 
		* sure the firstChild is the Activities Button in case some Extension is messing with it */	
		let leftBoxChildren = Main.panel._leftBox.get_children();
		let activitiesButton;
		
		for (let child in leftBoxChildren){
			/* All Panel Items are wrapped in another container, so we jump to the child of that*/	
			if(leftBoxChildren[child].get_child_at_index(0).name == "panelActivities"){
				activitiesButton = leftBoxChildren[child].get_child_at_index(0);			
			}
		}
		
		return activitiesButton;
	}
```
This goes into the enable function:
```
                /*Create the Icon for replacement*/
		iconActor = new St.Icon({ style_class: 'popup-menu-icon' });
		iconActor.icon_name = 'view-more-symbolic';
		
		/* Lets grab the ActivitiesButton Actor with our nice function */
		activitiesButtonActor = this.getActivitiesButton();
		
		/* We store the labelActor in our var so we can retrieve it in disable() */
		labelActor = activitiesButtonActor.label_actor;
		
		/* Now let's get rid of the Label*/	
		activitiesButtonActor.remove_actor(labelActor);
		
		/* And replace it with our Icon*/
		activitiesButtonActor.add_actor(iconActor);
```

And of course we might need to remove our stuff, so this goes into disable:

```
		/* Remove the Icon */
		activitiesButtonActor.remove_actor(iconActor);		
		
		/* we put the label back in*/	
		activitiesButtonActor.add_actor(labelActor);
		
		/* And we clean up our mess*/
		activitiesButtonActor = null;
		labelActor = null;
		iconActor = null;
```

Like i said, this could probably be prettied up a bit and of course we dont need 100 comments, but i made it like this so you know whats going on.

**Comment by cldx** [comment]
Looking good. Closing.
